package executar;

public class Start {
	
	/**	 
	 *  
	 * author felipeDevBino
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO
		
	}

	//ESCOLHE ATÉ 3 ATIVIDADES PRINCIPAIS PARA FAZER DE UMA VEZ, FORNECENDO AO USUÁRIO UMA
	//PEQUENA INTERFACE PARA DECREMENTAR O TEMPO DAS ATIVIDADES DIÁRIAS, E 2 ATIVIDADES SECUNDÁRIAS
	public static void selecionaAtividades() {		
		//TODO
	}
	
	/*
	 * QUESTIONA O USUÁRIO SE ELE GOSTARIA DE INSERIR A LOCALIZAÇÃO
	 * DE UM ARQUIVO CONTENDO INFORMAÇÕES PARA UMA LISTA EXISTENTE,
	 * O PROGRAMA BUSCARÁ PELA SEQUÊNCIA DE CARACTERES DAS ATIVIDADES 
	 * E ENTRETENIMENTOS E IRÁ VERIFICAR SE A FRASE FORMADA/INFORMAÇÃO 
	 * É VALIDA, INICIANDO O PROGRAMA SEM NECESSITAR DE INSERIR TODAS
	 * AS ATIVIDADES E HORÁRIOS NOVAMENTE.
	 */
	 public static void buscaListaEmDiretorios() {
		//TODO
	}
	
}
